package com.abhimanyu.vocabulate.db;
import java.util.*;
/**
 * Created by abhimanyu
 */
public class VocabulateData {
    public HashMap<String, String> VocabData()
    {
        HashMap<String, String> hm =new HashMap<>();
        // barrons 333 (~332)
        hm.put("abate", "to lessen");
        hm.put("aberrant", "abnormal");
        hm.put("abeyance", "suspended action");
        hm.put("abscond", "depart secretly and hide");
        hm.put("abstemious", "sparing in eating and\ndrinking temperate");
        hm.put("admonish", "warn");
        hm.put("adulterate", "make impure by adding\ninferior substances");
        hm.put("aesthetic", "appreciating the beautiful");
        hm.put("aggregate", "gather");
        hm.put("alacrity", "cheerful promptness");
        hm.put("alleviate", "relieve");
        hm.put("amalgamate", "combine");
        hm.put("ambiguous", "unclear");
        hm.put("ambivalence", "the state of having conflicting\nemotional attitudes");
        hm.put("ameliorate", "improve");
        hm.put("anachronism", "something or someone\nmisplaced in time");
        hm.put("analogous", "comparable");
        hm.put("anarchy", "absence of governing body");
        hm.put("anomalous", "abnormal");
        hm.put("antipathy", "aversion");
        hm.put("apathy", "lack of caring");
        hm.put("appease", "pacify");
        hm.put("apprise", "inform");
        hm.put("approbation", "approval");
        hm.put("appropriate", "acquire");
        hm.put("arduous", "hard");
        hm.put("artless", "without guile");
        hm.put("ascetic", "practicing self-denial");
        hm.put("assiduous", "diligent");
        hm.put("assuage", "ease");
        hm.put("attenuate", "make thinner");
        hm.put("audacious", "daring bold");
        hm.put("austere", "forbiddingly stern");
        hm.put("autonomous", "self-governing");
        hm.put("aver", "assert confidently");
        hm.put("banal", "hackneyed");
        hm.put("belie", "contradict");
        hm.put("beneficent", "kindly");
        hm.put("bolster", "support");
        hm.put("bombastic", "pompous");
        hm.put("boorish", "rude");
        hm.put("burgeon", "grow forth");
        hm.put("burnish", "make shiny by rubbing");
        hm.put("buttress", "support");
        hm.put("cacophonous", "discordant");
        hm.put("capricious", "unpredictable");
        hm.put("castigation", "punishment");
        hm.put("catalyst", "agent that speeds up a process");
        hm.put("caustic", "burning");
        hm.put("chicanery", "trickery");
        hm.put("coagulate", "thicken");
        hm.put("coda", "concluding section of a musical");
        hm.put("cogent", "convincing");
        hm.put("commensurate", "corresponding in degree");
        hm.put("compendium", "brief");
        hm.put("complaisant", "trying to please");
        hm.put("compliant", "yielding");
        hm.put("conciliatory", "reconciling");
        hm.put("condone", "overlook");
        hm.put("confound", "confuse");
        hm.put("connoisseur", "person competent to act\nas a judge of art");
        hm.put("contention", "claim");
        hm.put("contentious", "quarrelsome");
        hm.put("contrite", "penitent");
        hm.put("conundrum", "riddle");
        hm.put("converge", "approach");
        hm.put("convoluted", "coiled around");
        hm.put("craven", "cowardly");
        hm.put("daunt", "intimidate");
        hm.put("decorum", "propriety");
        hm.put("default", "failure to act");
        hm.put("deference", "courteous regard for another’s wish");
        hm.put("delineate", "portray");
        hm.put("denigrate", "blacken");
        hm.put("deride", "ridicule");
        hm.put("derivative", "unoriginal");
        hm.put("desiccate", "dry up");
        hm.put("desultory", "aimless");
        hm.put("deterrent", "something that discourage");
        hm.put("diatribe", "bitter scolding");
        hm.put("dichotomy", "split");
        hm.put("diffidence", "shyness");
        hm.put("diffuse", "wordy");
        hm.put("digression", "wandering away from the subject");
        hm.put("dirge", "lament with music");
        hm.put("disabuse", "correct a false impression");
        hm.put("discerning", "mentally quick and observant");
        hm.put("discordant", "not harmonious");
        hm.put("discredit", "defame");
        hm.put("discrepancy", "lack of consistency");
        hm.put("discrete", "separate");
        hm.put("disingenuous", "lacking genuine candor");
        hm.put("disinterested", "unprejudiced");
        hm.put("disjointed", "lacking coherence");
        hm.put("dismiss", "eliminate from consideration");
        hm.put("disparage", "belittle");
        hm.put("disparate", "basically different");
        hm.put("dissemble", "disguise");
        hm.put("disseminate", "distribute");
        hm.put("dissolution", "disintegration");
        hm.put("dissonance", "discord");
        hm.put("distend", "expend");
        hm.put("distill", "purify");
        hm.put("diverge", "vary");
        hm.put("divest", "strip");
        hm.put("document", "provide written evidence");
        hm.put("dogmatic", "opinionated");
        hm.put("dormant", "sleeping");
        hm.put("dupe", "someone easily fooled");
        hm.put("ebullient", "showing excitement");
        hm.put("eclectic", "selective");
        hm.put("efficacy", "power to produce desired effect");
        hm.put("effrontery", "impudence");
        hm.put("elegy", "poem");
        hm.put("elicit", "draw out by discussion");
        hm.put("embellish", "adorn");
        hm.put("empirical", "based on experience");
        hm.put("emulate", "imitate");
        hm.put("endemic", "prevailing among a specific\ngroup of people");
        hm.put("enervate", "weaken");
        hm.put("engender", "cause");
        hm.put("enhance", "increase");
        hm.put("ephemeral", "short-lived");
        hm.put("equanimity", "calmness of temperament");
        hm.put("equivocate", "lie");
        hm.put("erudite", "learned");
        hm.put("esoteric", "hard to understand");
        hm.put("eulogy", "expression of praise on the occasion\nof someone’s death");
        hm.put("euphemism", "mild expression in place of\nan unpleasant one");
        hm.put("exacerbate", "worsen");
        hm.put("exculpate", "clear from blame");
        hm.put("exigency", "urgent situation");
        hm.put("extrapolation", "projection");
        hm.put("facetious", "joking (often inappropriately)");
        hm.put("facilitate", "help bring about");
        hm.put("fallacious", "false");
        hm.put("fatuous", "brainless");
        hm.put("fawning", "trying to please\nby behaving obsequiously");
        hm.put("felicitous", "apt");
        hm.put("fervor", "glowing ardor");
        hm.put("flag", "droop");
        hm.put("fledgling", "inexperienced");
        hm.put("flout", "reject");
        hm.put("foment", "stir up");
        hm.put("forestall", "prevent by taking action in advance");
        hm.put("frugality", "thrift, economy");
        hm.put("futile", "useless");
        hm.put("gainsay", "deny");
        hm.put("garrulous", "loquacious");
        hm.put("goad", "urge on");
        hm.put("gouge", "overcharge");
        hm.put("grandiloquent", "pompous");
        hm.put("gregarious", "sociable");
        hm.put("guileless", "without deceit");
        hm.put("gullible", "easily deceived");
        hm.put("harangue", "long, passionate, and vehement speech");
        hm.put("homogeneous", "off the same kind");
        hm.put("hyperbole", "exaggeration");
        hm.put("iconoclastic", "attacking cherished traditions");
        hm.put("idolatry", "worship of idols");
        hm.put("immutable", "unchangeable");
        hm.put("impair", "injure");
        hm.put("impassive", "without feeling");
        hm.put("impede", "hinder");
        hm.put("impermeable", "impervious");
        hm.put("imperturbable", "calm placid");
        hm.put("impervious", "impenetrable");
        hm.put("implacable", "incapable of being pacified");
        hm.put("implicit", "understood but not stated");
        hm.put("implode", "burst inward");
        hm.put("inadvertently", "unintentionally");
        hm.put("inchoate", "recently begun");
        hm.put("incongruity", "lack of harmony");
        hm.put("inconsequential", "insignificant");
        hm.put("incorporate", "introduce something into\na larger whole");
        hm.put("indeterminate", "uncertain");
        hm.put("indigence", "poverty");
        hm.put("indolent", "lazy");
        hm.put("inert", "inactive");
        hm.put("ingenuous", "naïve and trusting");
        hm.put("inherent", "firmly established by nature");
        hm.put("innocuous", "harmless");
        hm.put("insensible", "unconscious");
        hm.put("insinuate", "hint");
        hm.put("insipid", "lacking in flavor");
        hm.put("insularity", "narrow-mindedness");
        hm.put("intractable", "unruly");
        hm.put("intransigence", "refusal of any compromise");
        hm.put("inundate", "overwhelm");
        hm.put("inured", "accustomed");
        hm.put("invective", "abuse");
        hm.put("irascible", "irritable");
        hm.put("irresolute", "uncertain how to act");
        hm.put("itinerary", "plan of a trip");
        hm.put("laconic", "brief and to the point");
        hm.put("lassitude", "languor");
        hm.put("latent", "potential but undeveloped");
        hm.put("laud", "praise");
        hm.put("lethargic", "drowsy");
        hm.put("levee", "earthen");
        hm.put("levity", "lack of seriousness");
        hm.put("log", "record of a voyage");
        hm.put("loquacious", "talkative");
        hm.put("lucid", "easily understood");
        hm.put("luminous", "shining");
        hm.put("magnanimity", "generosity");
        hm.put("malingerer", "one who feigns illness\nto escape duty");
        hm.put("malleable", "capable to being shaped by pounding");
        hm.put("maverick", "rebel");
        hm.put("mendacious", "lying");
        hm.put("metamorphosis", "change of form");
        hm.put("meticulous", "excessively careful");
        hm.put("misanthrope", "one who hates mankind");
        hm.put("mitigate", "appease");
        hm.put("mollify", "soothe");
        hm.put("morose", "ill-humored");
        hm.put("mundane", "worldly as opposed to spiritual");
        hm.put("negate", "cancel out");
        hm.put("neophyte", "recent convert");
        hm.put("obdurate", "stubborn");
        hm.put("obsequious", "slavishly attentive");
        hm.put("obviate", "make unnecessary");
        hm.put("occlude", "shut");
        hm.put("officious", "meddlesome");
        hm.put("onerous", "burdensome");
        hm.put("opprobrium", "infamy");
        hm.put("oscillate", "vibrate pendulumlike");
        hm.put("ostentatious", "showy");
        hm.put("paragon", "model of perfection");
        hm.put("partisan", "one-sided");
        hm.put("pathological", "pertaining to disease");
        hm.put("paucity", "scarcity");
        hm.put("pedantic", "showing off learning");
        hm.put("penchant", "strong inclination");
        hm.put("penury", "severe poverty");
        hm.put("perennial", "something long-lasting");
        hm.put("perfidious", "treacherous");
        hm.put("perfunctory", "superficial");
        hm.put("permeable", "penetrable");
        hm.put("pervasive", "spread throughout");
        hm.put("phlegmatic", "clam");
        hm.put("piety", "devoutness");
        hm.put("placate", "pacify");
        hm.put("plasticity", "ability to be molded");
        hm.put("platitude", "trite remark");
        hm.put("plethora", "excess");
        hm.put("plummet", "fall sharply");
        hm.put("porous", "full of pores");
        hm.put("pragmatic", "practical (as opposed to idealistic)");
        hm.put("preamble", "introductory statement");
        hm.put("precarious", "uncertain");
        hm.put("precipitate", "rash");
        hm.put("precursor", "forerunner");
        hm.put("presumptuous", "arrogant");
        hm.put("prevaricate", "lie");
        hm.put("probity", "uprightness");
        hm.put("problematic", "doubtful");
        hm.put("prodigal", "wasteful");
        hm.put("profound", "deep");
        hm.put("prohibitive", "tending to prevent the use\nof something");
        hm.put("proliferate", "grow rapidly");
        hm.put("propensity", "natural inclination");
        hm.put("propitiate", "appease");
        hm.put("propriety", "correct or appropriate behaviour");
        hm.put("proscribe", "ostracize");
        hm.put("pungent", "stinging");
        hm.put("qualified", "limited");
        hm.put("quibble", "minor objection");
        hm.put("quiescent", "at rest");
        hm.put("rarefied", "made less dense (of a gas)");
        hm.put("recalcitrant", "obstinately stubborn");
        hm.put("recant", "disclaim of disavow");
        hm.put("recluse", "hermit");
        hm.put("recondite", "abstruse");
        hm.put("refractory", "stubborn, unmanageable");
        hm.put("refute", "disprove");
        hm.put("relegate", "banish to an inferior position");
        hm.put("reproach", "express disapproval");
        hm.put("reprobate", "person hardened in sin");
        hm.put("repudiate", "disown");
        hm.put("rescind", "cancel");
        hm.put("resolution", "determination");
        hm.put("resolve", "determination");
        hm.put("reticent", "reserved");
        hm.put("reverent", "respectful");
        hm.put("sage", "person celebrated for wisdom");
        hm.put("salubrious", "healthful");
        hm.put("sanction", "approve");
        hm.put("satiate", "satisfy fully");
        hm.put("saturate", "soak thoroughly");
        hm.put("savor", "enjoy");
        hm.put("secrete", "hide away");
        hm.put("shard", "fragment, generally of pottery");
        hm.put("skeptic", "doubter");
        hm.put("solicitous", "worried, concerned");
        hm.put("soporific", "sleep-causing");
        hm.put("specious", "seemingly reasonable but incorrect");
        hm.put("spectrum", "color band produced when\na beam of light passes through a prism");
        hm.put("sporadic", "occurring irregularly");
        hm.put("stigma", "token of disgrace");
        hm.put("stint", "be thrifty");
        hm.put("stipulate", "make express conditions, specify");
        hm.put("stolid", "dull");
        hm.put("striated", "marked with parallel bands");
        hm.put("strut", "pompous walk");
        hm.put("subpoena", "writ summoning a witness to appear");
        hm.put("subside", "settle down");
        hm.put("substantiate", "establish by evidence");
        hm.put("supersede", "cause to be set aside");
        hm.put("supposition", "hypothesis");
        hm.put("tacit", "understood");
        hm.put("tangential", "peripheral");
        hm.put("tenuous", "thin");
        hm.put("tirade", "extended scolding");
        hm.put("torpor", "lethargy");
        hm.put("tortuous", "winding");
        hm.put("tractable", "docile");
        hm.put("transgression", "violation of a law");
        hm.put("truculence", "aggressiveness");
        hm.put("vacillate", "waver");
        hm.put("venerate", "revere");
        hm.put("veracious", "truthful");
        hm.put("verbose", "wordy");
        hm.put("viable", "practical");
        hm.put("viscous", "sticky, gluey");
        hm.put("vituperative", "abusive");
        hm.put("volatile", "changeable");
        hm.put("warranted", "justified");
        hm.put("wary", "very cautious");
        hm.put("welter", "turmoil");
        hm.put("whimsical", "capricious");
        hm.put("zealot", "fanatic");

        //kaplan's 400-29 = 371
        hm.put("abdicate", "to give up a position");
        hm.put("abjure", "to reject");
        hm.put("ablution", "act of cleansing");
        hm.put("abnegate", "to deny, renounce");
        hm.put("abrogate", "to abolish");
//        hm.put("abstemious", "consuming moderately");
        hm.put("abstruse", "difficult to comprehend");
        hm.put("abut", "to be in contact with");
        hm.put("acerbic", "bitter");
        hm.put("acme", "highest point");
        hm.put("acquiesce", "to agree in silence");
        hm.put("adroit", "skillful");
        hm.put("adumbrate", "to outline in a\nshadowy way");
        hm.put("aerie", "nest built high in\nthe air");
        hm.put("altruism", "unselfish concern for\nothers’ welfare");
        hm.put("ambulatory", "itinerant");
        hm.put("amortize", "to diminish by installment\npayments");
        hm.put("ancillary", "subordinate");
        hm.put("antediluvian", "ancient beyond measure");
        hm.put("anthropomorphic", "attributing human qualities\nto nonhumans");
        hm.put("aplomb", "confidence");
        hm.put("apostate", "one who renounces a\nreligious faith");
        hm.put("apothegm", "a short, instructive saying");
        hm.put("apotheosis", "deification");
        hm.put("arboreal", "relating to trees");
//        hm.put("assiduous", "hardworking");
        hm.put("bacchanalian", "drunkenly festive");
        hm.put("balk", "to refuse");
        hm.put("beatific", "saintly");
        hm.put("behemoth", "huge creature");
//        hm.put("belie", "to misrepresent");
        hm.put("benison", "blessing");
        hm.put("bifurcate", "divide into two parts");
        hm.put("bilious", "easily irritated");
        hm.put("bonhomie", "good-natured geniality");
        hm.put("bulwark", "defense wall");
        hm.put("cajole", "to flatter");
        hm.put("calamitous", "disastrous");
        hm.put("calumny", "false and malicious accusation");
        hm.put("canard", "a lie");
        hm.put("carom", "to strike and rebound");
        hm.put("cavalcade", "a procession");
        hm.put("chagrin", "embarrassment");
        hm.put("charlatan", "fake");
        hm.put("chattel", "piece of personal property");
        hm.put("chimerical", "imaginary");
        hm.put("choleric", "short-tempered");
        hm.put("churlish", "rude");
        hm.put("cistern", "tank for rainwater");
        hm.put("coalesce", "to grow together");
        hm.put("coffer", "large chest for money");
        hm.put("cognomen", "family name");
        hm.put("comeliness", "physical grace and beauty");
        hm.put("commodious", "spacious");
        hm.put("compunctious", "feeling guilty");
//        hm.put("conciliatory", "overcoming distrust");
        hm.put("conflagration", "big, destructive fire");
        hm.put("congenial", "similar in tastes and habits");
        hm.put("consanguineous", "of the same origin");
//        hm.put("contentious", "quarrelsome");
        hm.put("contumacious", "rebellious");
        hm.put("corpulence", "obesity");
        hm.put("corrugate", "to mold in a shape with\nparallel grooves and ridges");
        hm.put("cosset", "to pamper");
        hm.put("coterie", "small group of persons with\na similar purpose");
        hm.put("coven", "group of witches");
        hm.put("curmudgeon", "cranky person");
        hm.put("declivity", "downward slope");
        hm.put("deleterious", "destructive");
        hm.put("deluge", "flood");
        hm.put("demagogue", "leader who uses appeals\nto emotion or prejudice");
//        hm.put("denigrate", "to slur or blacken\nsomeone’s reputation");
        hm.put("descry", "to discover or reveal");
        hm.put("diaphanous", "allowing light to\nshow through");
        hm.put("dictum", "authoritative statement");
        hm.put("didactic", "excessively instructive");
        hm.put("diluvial", "relating to a flood");
        hm.put("diminutive", "small");
        hm.put("discomfit", "to cause embarrassment");
        hm.put("distaff", "the female branch of\na family");
        hm.put("dither", "to act confusedly or\nwithout clear purpose");
        hm.put("diurnal", "daily");
        hm.put("doctrinaire", "rigidly devoted to theories");
        hm.put("dolor", "sadness");
        hm.put("doughty", "courageous");
        hm.put("droll", "amusing in a subtle way");
        hm.put("dyspeptic", "suffering from indigestion");
//        hm.put("ebullient", "exhilarated");
        hm.put("effluvia", "outpouring of gases or vapors");
        hm.put("effulgent", "brilliantly shining");
        hm.put("egregious", "conspicuously bad");
        hm.put("emend", "to correct a text");
        hm.put("emollient", "having soothing qualities");
        hm.put("encomium", "warm praise");
//        hm.put("endemic", "belonging to a particular area");
        hm.put("ennui", "boredom");
        hm.put("epicure", "person with refined taste\nin food and wine");
        hm.put("epitome", "representative of an entire group");
        hm.put("ersatz", "fake");
        hm.put("eschew", "avoid");
        hm.put("evince", "display");
        hm.put("exorcise", "to expel evil spirits");
        hm.put("expatiate", "to wander");
        hm.put("expiate", "make amends for");
        hm.put("expunge", "eliminate completely");
        hm.put("expurgate", "to censor");
        hm.put("extemporaneous", "unrehearsed");
        hm.put("extol", "to praise");
        hm.put("extrapolate", "to estimate");
//        hm.put("facetious", "witty in an\ninappropriate way");
//        hm.put("fatuous", "stupid");
        hm.put("fealty", "intense loyalty");
        hm.put("fecund", "fruitful");
        hm.put("fetid", "foul-smelling");
        hm.put("fey", "doomed");
        hm.put("filch", "to steal");
        hm.put("filial", "appropriate for a child");
        hm.put("flaccid", "weak");
        hm.put("foliate", "to grow");
        hm.put("forswear", "reject");
        hm.put("fracas", "noisy dispute");
        hm.put("fractious", "rebellious");
        hm.put("frenetic", "wildly frantic");
        hm.put("fulminate", "to explode with anger");
        hm.put("fulsome", "excessive");
        hm.put("furtive", "secret");
//        hm.put("gainsay", "to deny");
        hm.put("gambol", "to dance around playfully");
        hm.put("gauche", "socially awkward");
        hm.put("germinate", "to begin to grow");
        hm.put("gibe", "taunting remarks");
        hm.put("glib", "fluent in an\ninsincere manner");
        hm.put("gnostic", "having to do with\nknowledge");
        hm.put("grandiloquence", "pompous talk");
        hm.put("gratuitous", "voluntary");
        hm.put("gustatory", "relating to sense of taste");
        hm.put("hackneyed", "worn out by over-use");
//        hm.put("harangue", "a pompous speech");
        hm.put("hegemony", "domination");
        hm.put("heretical", "opposed to an established\nreligious orthodoxy");
        hm.put("hermetic", "tightly sealed");
        hm.put("hoary", "very old");
        hm.put("husband", "to farm");
        hm.put("idiosyncrasy", "peculiarity of temperament");
        hm.put("ignominious", "disgraceful and dishonorable");
        hm.put("ilk", "type or kind");
        hm.put("illusory", "unreal");
        hm.put("imbue", "to infuse");
        hm.put("impecunious", "poor");
        hm.put("imperious", "arrogantly self-assured");
        hm.put("impolitic", "unwise");
        hm.put("impromptu", "spontaneous");
        hm.put("impugn", "to call into question");
        hm.put("incarnate", "having bodily form");
        hm.put("incendiary", "flammable");
        hm.put("inculcate", "to teach");
        hm.put("inculpate", "to blame");
        hm.put("indefatigable", "never tired");
        hm.put("indigent", "very poor");
//        hm.put("indolent", "habitually lazy");
        hm.put("indubitable", "unquestionable");
//        hm.put("inert", "tending to inactivity");
        hm.put("infallible", "incapable of making\na mistake");
        hm.put("ingenious", "clever");
        hm.put("ingratiate", "to bring oneself purposely\ninto another’s good graces");
        hm.put("ingress", "entrance");
        hm.put("innuendo", "indirect and subtle criticism");
        hm.put("insidious", "devious");
        hm.put("insuperable", "unconquerable");
        hm.put("interdict", "prohibit");
        hm.put("interlocutor", "someone taking part in\na dialogue");
        hm.put("interloper", "trespasser");
        hm.put("internecine", "deadly to both sides");
        hm.put("interpolate", "to insert");
        hm.put("interstice", "a space between things");
        hm.put("intimation", "clue");
        hm.put("intrepid", "fearless");
        hm.put("intrinsic", "inherent, internal");
        hm.put("inure", "to harden");
        hm.put("inveterate", "confirmed");
        hm.put("invidious", "likely to provoke ill will");
        hm.put("itinerant", "wandering from place\nto place");
        hm.put("jibe", "to shift suddenly from\none side to the other");
        hm.put("jingoism", "belligerent support of one’s\ncountry");
        hm.put("jocular", "playful");
        hm.put("juggernaut", "huge force destroying\neverything in its path");
        hm.put("jurisprudence", "philosophy of law");
        hm.put("kismet", "fate");
        hm.put("knell", "sound of a funeral bell");
        hm.put("lachrymose", "tearful");
        hm.put("lambaste", "disapprove angrily");
        hm.put("lapidary", "relating to precious stones");
        hm.put("largess", "generosity");
//        hm.put("lassitude", "lethargy");
        hm.put("legerdemain", "trickery");
//        hm.put("levity", "humor, frivolity");
        hm.put("lexicon", " list of words");
        hm.put("libidinous", "lustful");
        hm.put("licentious", "immoral");
        hm.put("limpid", "clear and simple in style");
        hm.put("liniment", "medicinal liquid used\nexternally to ease pain");
        hm.put("lionize", "to treat as a celebrity");
        hm.put("lissome", "easily flexed");
        hm.put("lugubrious", "sorrowful");
        hm.put("macabre", "gruesome");
        hm.put("machination", "plot or scheme");
        hm.put("malapropism", "humorous misuse\nof a word");
        hm.put("malevolent", "ill-willed");
        hm.put("manifold", "diverse");
        hm.put("martinet", "strict disciplinarian");
        hm.put("maudlin", "overly sentimental");
        hm.put("mawkish", "sickeningly sentimental");
        hm.put("megalomania", "mental state with delusions\nof wealth and power");
//        hm.put("mendacious", "dishonest");
        hm.put("mendicant", "beggar");
        hm.put("mercurial", "quick, shrewd, and\nunpredictable");
        hm.put("meritorious", "deserving reward or praise");
        hm.put("minatory", "threatening");
        hm.put("mnemonic", "relating to memory");
        hm.put("molt", "to shed hair, skin,\nor an outer layer periodically");
        hm.put("mordacious", "caustic");
        hm.put("mote", "small particle");
        hm.put("multifarious", "diverse");
        hm.put("munificent", "generous");
        hm.put("nadir", "lowest point");
        hm.put("nascent", "coming into existence");
        hm.put("nebulous", "vague");
        hm.put("necromancy", "black magic");
        hm.put("nefarious", "vicious");
        hm.put("neologism", "new word or expression");
//        hm.put("neophyte", "novice");
        hm.put("nihilism", "belief that existence and all\ntraditional values are meaningless");
        hm.put("noisome", "stinking, putrid");
        hm.put("noxious", "harmful");
        hm.put("numismatics", "coin collecting");
        hm.put("obfuscate", "to confuse");
        hm.put("obstreperous", "troublesome");
        hm.put("omnipotent", "having unlimited power");
        hm.put("omniscient", "having infinite knowledge");
//        hm.put("oscillate", "to move back and forth");
        hm.put("ouster", "expulsion");
        hm.put("paean", "a song of praise\nor thanksgiving");
        hm.put("palliate", "to make less serious");
        hm.put("panacea", "cure-all");
        hm.put("panegyric", "elaborate praise");
        hm.put("panoply", "impressive array");
        hm.put("parley", "discussion between enemies");
        hm.put("parochial", "of limited scope or outlook");
        hm.put("parsimony", "stinginess");
        hm.put("pastiche", "piece of literature or\nmusic imitating other works");
//        hm.put("paucity", "scarcity, lack");
        hm.put("peccadillo", "minor sin");
        hm.put("peculation", "theft of money or goods");
//        hm.put("penchant", "inclination");
        hm.put("penultimate", "next to last");
        hm.put("penumbra", "partial shadow");
        hm.put("perambulate", "walk about");
        hm.put("periphrastic", "using circumlocution");
        hm.put("pernicious", "very harmful");
        hm.put("perspicacious", "shrewd");
        hm.put("pertinacious", "persistent");
        hm.put("phalanx", "massed group of soldiers,\npeople, or things");
        hm.put("philistine", "narrow-minded person");
        hm.put("plait", "to braid");
        hm.put("plangent", "resounding");
        hm.put("plaudit", "applause");
        hm.put("pneumatic", "relating to air");
        hm.put("polemic", "controversy, argument");
        hm.put("polyglot", "speaker of many languages");
        hm.put("posit", "to put in position");
        hm.put("precept", "principle");
//        hm.put("precursor", "predecessor");
        hm.put("predilection", "preference");
        hm.put("prescient", "having foresight");
        hm.put("privation", "lack of usual necessities\nor comforts");
//        hm.put("probity", "high-mindedness");
        hm.put("progenitor", "ancestor in a direct line");
        hm.put("prognosticate", "to predict");
        hm.put("prolific", "productive");
        hm.put("prolix", "tedious");
        hm.put("promulgate", "to make known publicly");
        hm.put("propinquity", "nearness");
        hm.put("propitious", "favorable");
        hm.put("proselytize", "to induce someone to convert to\na particular belief or religion");
        hm.put("prostrate", "lying face downward,\nlying flat on the ground");
        hm.put("protagonist", "main character in a\nplay or story");
        hm.put("provident", "prudent");
        hm.put("provincial", "limited in scope");
        hm.put("prurient", "exhibiting lewd desires");
        hm.put("puerile", "immature");
        hm.put("pulchritude", "beauty");
        hm.put("pundit", "an authority or critic");
        hm.put("pusillanimous", "cowardly");
        hm.put("querulous", "inclined to complain");
        hm.put("quotidian", "occurring daily");
        hm.put("raconteur", "a witty storyteller");
        hm.put("raillery", "lighthearted jesting");
        hm.put("rancor", "bitter hatred");
        hm.put("rapacious", "greedy");
        hm.put("rapprochement", "reestablishing a cordial\nrelationship");
        hm.put("raze", "to tear down");
//        hm.put("recalcitrant", "resisting authority or control");
        hm.put("recidivism", "tendency to repeat previous\nbehavior");
//        hm.put("recondite", "relating to obscure learning");
        hm.put("recreant", "disloyal");
        hm.put("redress", "relief from wrong or injury");
        hm.put("rejoinder", "response");
        hm.put("renege", "to go back on one’s word");
        hm.put("renitent", "resisting pressure");
        hm.put("repast", "meal");
//        hm.put("reprobate", "morally unprincipled person");
        hm.put("requite", "to return or repay");
        hm.put("respite", "interval of relief");
        hm.put("restive", "impatient");
        hm.put("retinue", "group of attendants with\nan important person");
        hm.put("revelry", "boisterous festivity");
        hm.put("ribald", "humorous in a vulgar way");
        hm.put("riposte", "a retort");
        hm.put("rococo", "very highly ornamented");
        hm.put("rotund", "round in shape");
        hm.put("ruminate", "to contemplate");
        hm.put("sacrosanct", "extremely sacred");
        hm.put("sagacious", "shrewd, wise");
        hm.put("salacious", "lustful");
//        hm.put("salubrious", "healthful");
        hm.put("sanguine", "ruddy");
        hm.put("sapient", "wise");
        hm.put("scabbard", "sheath for sword");
        hm.put("scintilla", "very small amount");
        hm.put("scintillate", "to sparkle");
        hm.put("scurrilous", "vulgar");
        hm.put("sedition", "behavior promoting rebellion");
        hm.put("senescent", "aging");
        hm.put("sentient", "aware");
        hm.put("sepulchral", "typical of a place of\nburial");
        hm.put("seraphic", "angelic");
        hm.put("shirk", "to avoid a task due to\nlaziness or fear");
        hm.put("simper", "smile foolishly");
        hm.put("sinecure", "well-paying job that\nrequires little or no work");
        hm.put("sinuous", "winding");
        hm.put("slake", "to quench or moderate");
        hm.put("slovenly", "messy");
        hm.put("sojourn", "stay");
        hm.put("solecism", "grammatical mistake");
        hm.put("solipsism", "belief that the self\nis the only reality");
        hm.put("somnambulist", "sleepwalker");
        hm.put("sonorous", "producing a full,\nrich sound");
        hm.put("sophist", "person good at arguing\ndeviously");
        hm.put("sportive", "frolicsome");
        hm.put("squalid", "filthy");
        hm.put("staid", "self-restrained");
        hm.put("stentorian", "extremely loud");
        hm.put("striate", "grooved");
        hm.put("stringent", "imposing rigorous standards");
        hm.put("stymie", "to block or thwart");
        hm.put("subterfuge", "trick used to avoid\nsomething");
        hm.put("sully", "to stain");
        hm.put("supercilious", "arrogant");
        hm.put("surly", "rude and bad-tempered");
        hm.put("surreptitious", "characterized by secrecy");
        hm.put("sybarite", "person devoted to pleasure\nand luxury");
        hm.put("sycophant", "self-serving flatterer");
        hm.put("syncopation", "temporary irregularity in\nmusical rhythm");
        hm.put("tableau", "vivid description");
        hm.put("talisman", "something producing a\nmagical effect");
        hm.put("tantamount", "equivalent in value");
        hm.put("temerity", "recklessness");
        hm.put("temporal", "relating to time");
        hm.put("tenable", "reasonable");
        hm.put("tenet", "belief");
//        hm.put("tenuous", "weak");
        hm.put("threnody", "a sad poem or song");
        hm.put("trammel", "to impede or hamper");
        hm.put("trenchant", "acute");
        hm.put("trite", "superficial");
        hm.put("truculent", "savage and cruel");
        hm.put("turgid", "bloated");
        hm.put("turpitude", "inherent vileness");
        hm.put("tyro", "beginnere");
        hm.put("umbrage", "resentment");
        hm.put("unctuous", "greasy");
        hm.put("unfettered", "free");
        hm.put("unsullied", "clean");
        hm.put("untoward", "not favorable");
        hm.put("urbane", "courteous");
        hm.put("usury", "lending money at exorbitant\nrates");
        hm.put("vacuous", "empty");
        hm.put("variegated", "varied");
        hm.put("virile", "manly");
//        hm.put("viscous", "thick");
        hm.put("vitiate", "reduce in value");
        hm.put("vitriolic", "burning");
        hm.put("vituperate", "to abuse verbally");
        hm.put("vociferous", "loud");
        hm.put("voluble", "talkative");
        hm.put("waspish", "easily irritated");
        hm.put("wizened", "wrinkled");
        hm.put("wraith", "a ghost");
        hm.put("xenophobia", "fear or hatred of\nforeigners or strangers");
        hm.put("zenith", "highest point");



        return hm;
    }
}
